/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Tusk.Model
{
    /// <summary>
    /// TrackingShipment
    /// </summary>
    [DataContract(Name = "TrackingShipment")]
    public partial class TrackingShipment : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingShipment" /> class.
        /// </summary>
        /// <param name="shipmentId">shipmentId.</param>
        /// <param name="trackingNumber">trackingNumber.</param>
        /// <param name="labels">labels.</param>
        public TrackingShipment(int shipmentId = default(int), string trackingNumber = default(string), List<TrackingShipmentLabel> labels = default(List<TrackingShipmentLabel>))
        {
            this.ShipmentId = shipmentId;
            this.TrackingNumber = trackingNumber;
            this.Labels = labels;
        }

        /// <summary>
        /// Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name = "shipment_id", EmitDefaultValue = false)]
        public int ShipmentId { get; set; }

        /// <summary>
        /// Gets or Sets TrackingNumber
        /// </summary>
        [DataMember(Name = "tracking_number", EmitDefaultValue = false)]
        public string TrackingNumber { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [DataMember(Name = "labels", EmitDefaultValue = false)]
        public List<TrackingShipmentLabel> Labels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackingShipment {\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  TrackingNumber: ").Append(TrackingNumber).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
