/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Tusk.Client;
using Tusk.Api;
// uncomment below to import models
//using Tusk.Model;

namespace Tusk.Test.Api
{
    /// <summary>
    ///  Class for testing LabelsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LabelsApiTests : IDisposable
    {
        private LabelsApi instance;

        public LabelsApiTests()
        {
            instance = new LabelsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LabelsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LabelsApi
            //Assert.IsType<LabelsApi>(instance);
        }

        /// <summary>
        /// Test GetaLabelbyID
        /// </summary>
        [Fact]
        public void GetaLabelbyIDTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int labelId = null;
            //var response = instance.GetaLabelbyID(labelId);
            //Assert.IsType<Label>(response);
        }

        /// <summary>
        /// Test PurchaseLabels
        /// </summary>
        [Fact]
        public void PurchaseLabelsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1LabelsRequest? v1LabelsRequest = null;
            //var response = instance.PurchaseLabels(v1LabelsRequest);
            //Assert.IsType<ShipmentPurchaseResponse>(response);
        }

        /// <summary>
        /// Test VoidaLabel
        /// </summary>
        [Fact]
        public void VoidaLabelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int labelId = null;
            //instance.VoidaLabel(labelId);
        }
    }
}
